# Generated by Django 4.2.22 on 2026-07-30 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_availability_product_cost_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='tourplan',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='tourplan',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
