# Generated by Django 4.2.22 on 2026-08-05 05:58

from django.db import migrations, models
import django.db.models.deletion


def get_or_create_tax(Tax, rate):
    existing = Tax.objects.filter(rate=rate).first()
    if existing:
        return existing
    return Tax.objects.create(
        tax_id=f'TAX-{rate}',
        name=f'Tax {rate}%',
        rate=rate,
        status='active',
        applied_to='both',
    )


def backfill_product_tax(apps, schema_editor):
    Product = apps.get_model('products', 'Product')
    Tax = apps.get_model('finance', 'Tax')

    for row in Product.objects.all():
        rate = row.tax_decimal_tmp
        if rate:
            tax = get_or_create_tax(Tax, rate)
            Product.objects.filter(pk=row.pk).update(tax=tax)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_tax_from_taxrate'),
        ('products', '0007_stocktransfer_stockadjustment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='tax_percentage',
            new_name='tax_decimal_tmp',
        ),
        migrations.AddField(
            model_name='product',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to this product.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='products', to='finance.tax'),
        ),
        migrations.RunPython(backfill_product_tax),
        migrations.RemoveField(
            model_name='product',
            name='tax_decimal_tmp',
        ),
    ]
