from django.urls import path
from . import views

urlpatterns = [
    path('departments/', views.DepartmentListCreateView.as_view()),
    path('departments/<int:pk>/', views.DepartmentDetailView.as_view()),
    path('designations/', views.DesignationListCreateView.as_view()),
    path('designations/<int:pk>/', views.DesignationDetailView.as_view()),
    path('custom-fields/', views.CustomFieldListCreateView.as_view()),
    path('custom-fields/<int:pk>/', views.CustomFieldDetailView.as_view()),
    path('prefixes/', views.PrefixSettingListCreateView.as_view()),
    path('prefixes/<int:pk>/', views.PrefixSettingDetailView.as_view()),
    path('prefixes/<int:pk>/next/', views.PrefixSettingNextNumberView.as_view()),
    path('printers/', views.PrinterSettingListCreateView.as_view()),
    path('printers/<int:pk>/', views.PrinterSettingDetailView.as_view()),
    path('gdpr/', views.GDPRConsentListCreateView.as_view()),
    path('localization/', views.LocalizationSettingView.as_view()),
    path('languages/', views.LanguageSettingListCreateView.as_view()),
    path('languages/<int:pk>/', views.LanguageSettingDetailView.as_view()),
    path('appearance/', views.AppearanceSettingView.as_view()),
    path('invoice-settings/', views.InvoiceSettingView.as_view()),
    path('security-settings/', views.SecuritySettingView.as_view()),
    path('countries/', views.CountryListCreateView.as_view()),
    path('countries/<int:pk>/', views.CountryDetailView.as_view()),
    path('sms-gateways/', views.SmsGatewayListCreateView.as_view()),
    path('sms-gateways/<int:pk>/', views.SmsGatewayDetailView.as_view()),
    path('email-settings/', views.EmailSettingView.as_view()),
    path('storage-settings/', views.StorageSettingView.as_view()),
    path('system-update/', views.SystemUpdateView.as_view()),
    path('notification-settings/', views.NotificationSettingListCreateView.as_view()),
    path('notification-settings/<int:pk>/', views.NotificationSettingDetailView.as_view()),
]
