# Generated by Django 4.2.22 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='contract',
            name='contract_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contract',
            name='signature',
            field=models.TextField(blank=True),
        ),
    ]
