# Generated by Django 4.2.30 on 2026-09-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hytech_customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="BaseService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("ServiceName", models.CharField(max_length=200)),
                (
                    "ServiceNameGu",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "Category",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("GOVT_FORMS", "Government Forms — Current Services"),
                            ("CARD_SERVICES", "Update / Card Services"),
                            ("NEW_SERVICES", "New Services"),
                            ("OTHER_SERVICES", "Other Center Services"),
                            ("COMPUTER_COURSES", "Computer Courses"),
                            ("ADDITIONAL_SERVICES", "Additional Services"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "SubCategory",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("Department", models.CharField(blank=True, max_length=200, null=True)),
                (
                    "ServiceType",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("NEW", "New"),
                            ("UPDATE", "Update"),
                            ("RENEWAL", "Renewal"),
                            ("KYC", "KYC"),
                            ("OTHER", "Other"),
                        ],
                        default="NEW",
                        max_length=50,
                        null=True,
                    ),
                ),
                ("Description", models.TextField(blank=True, null=True)),
                (
                    "GovernmentFee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "ServiceCharge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "TotalFee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("SlaDays", models.PositiveIntegerField(default=7)),
                (
                    "Priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("SmsTemplateGu", models.TextField(blank=True, null=True)),
                ("SmsTemplateEn", models.TextField(blank=True, null=True)),
                ("StaffInstructions", models.TextField(blank=True, null=True)),
                ("FormFields", models.JSONField(blank=True, default=list)),
                ("PortalUrl", models.URLField(blank=True, max_length=500, null=True)),
                ("IsOfficial", models.BooleanField(default=True)),
                ("IsActive", models.BooleanField(default=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="SubService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("SubServiceName", models.CharField(max_length=200)),
                ("Description", models.TextField(blank=True, null=True)),
                ("IsActive", models.BooleanField(default=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                ("UpdatedAt", models.DateTimeField(auto_now=True)),
                (
                    "Service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sub_services",
                        to="hytech_services.baseservice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="Transaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "transaction_date",
                    models.DateField(default=django.utils.timezone.now),
                ),
                (
                    "bill_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "paid_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "due_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[
                            ("PAID", "Paid"),
                            ("PARTIAL", "Partial"),
                            ("PENDING", "Pending"),
                        ],
                        default="PAID",
                        max_length=20,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[
                            ("CASH", "Cash"),
                            ("ONLINE/UPI", "Online / UPI"),
                            ("CARD", "Card"),
                            ("UPI", "UPI"),
                            ("WALLET", "Wallet"),
                            ("BANK_TRANSFER", "Bank Transfer"),
                            ("ONLINE", "Online"),
                        ],
                        default="CASH",
                        max_length=30,
                    ),
                ),
                ("points_earned", models.IntegerField(default=0)),
                ("employee_points", models.IntegerField(default=0)),
                ("points_redeemed", models.IntegerField(default=0)),
                (
                    "wallet_credit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "wallet_used",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "net_wallet_change",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "previous_due_cleared",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("remarks", models.TextField(blank=True, null=True)),
                ("items", models.JSONField(blank=True, default=list)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transactions",
                        to="hytech_customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="hytech_services.baseservice",
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="staff_transactions",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "sub_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="transactions",
                        to="hytech_services.subservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="RequiredDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("DocumentName", models.CharField(max_length=200)),
                ("document_type", models.CharField(default="AADHAR", max_length=50)),
                ("IsRequired", models.BooleanField(default=True)),
                ("CreatedAt", models.DateTimeField(auto_now_add=True)),
                (
                    "SubService",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="required_documents",
                        to="hytech_services.subservice",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
