# Generated by Django 4.2.22 on 2026-08-05 06:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('calendar_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='holiday',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='holiday',
            name='type',
            field=models.CharField(choices=[('public', 'Public'), ('government', 'Government'), ('optional', 'Optional'), ('restricted', 'Restricted'), ('other', 'Other')], default='public', max_length=20),
        ),
    ]
