# Generated by Django 4.2.22 on 2026-08-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customerfeedback'),
        ('finance', '0005_payroll'),
        ('pipeline', '0006_lead_product_requirement_lead_quantity'),
        ('orders', '0003_quotation_quotationitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='customer',
            field=models.ForeignKey(blank=True, help_text='Customer record linked to this quotation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='sales.customer'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='delivery_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='quotation',
            name='gst_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='lead',
            field=models.ForeignKey(blank=True, help_text='Lead this quotation originated from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='pipeline.lead'),
        ),
        migrations.AddField(
            model_name='quotation',
            name='payment_terms',
            field=models.CharField(choices=[('advance', 'Advance'), ('due_on_receipt', 'Due on Receipt'), ('net_7', 'Net 7'), ('net_15', 'Net 15'), ('net_30', 'Net 30'), ('net_45', 'Net 45'), ('net_60', 'Net 60'), ('cogd', 'Cash on Goods Delivery')], default='net_30', max_length=20),
        ),
        migrations.AddField(
            model_name='quotation',
            name='shipping_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='quotation',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='GST / tax applied to the subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='quotations', to='finance.tax'),
        ),
    ]
