# Generated by Django 4.2.22 on 2026-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_quotation_customer_quotation_delivery_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='quotation',
            name='quote_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
