# Generated by Django 4.2.22 on 2026-08-07 06:59

from django.db import migrations, models

DEFAULT_STAGES = [
    'cutting',
    'fabrication',
    'machining',
    'welding',
    'grinding',
    'painting',
    'assembly',
    'qc',
]


def seed_default_stages(apps, schema_editor):
    ProductionStage = apps.get_model('production', 'ProductionStage')
    ProductionStage.objects.bulk_create([
        ProductionStage(name=name, sequence=index)
        for index, name in enumerate(DEFAULT_STAGES, start=1)
    ])


def unseed_default_stages(apps, schema_editor):
    ProductionStage = apps.get_model('production', 'ProductionStage')
    ProductionStage.objects.all().delete()


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductionStage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('sequence', models.PositiveIntegerField(unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Production Stage',
                'verbose_name_plural': 'Production Stages',
                'ordering': ['sequence'],
            },
        ),
        migrations.RunPython(seed_default_stages, unseed_default_stages),
    ]
