# Generated by Django 4.2.22 on 2026-08-31 07:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('production', '0002_productionstage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('worker_code', models.CharField(blank=True, max_length=20, unique=True)),
                ('worker_type', models.CharField(choices=[('cutting', 'Cutting'), ('bending', 'Bending'), ('welding', 'Welding'), ('painting', 'Painting'), ('assembly', 'Assembly'), ('quality_check', 'Quality Check'), ('packing', 'Packing'), ('other', 'Other')], default='other', max_length=20)),
                ('skill_level', models.CharField(choices=[('junior', 'Junior'), ('senior', 'Senior'), ('supervisor', 'Supervisor')], default='junior', max_length=20)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('machine', models.ForeignKey(blank=True, help_text='Machine this worker operates.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='production.machine')),
                ('user', models.OneToOneField(help_text='Benefit of being a User: the worker gets check-in/checkout, attendance and leave exactly like an employee.', on_delete=django.db.models.deletion.CASCADE, related_name='production_worker_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['user__first_name', 'user__last_name'],
            },
        ),
    ]
