# Generated by Django 4.2.22 on 2026-08-31 07:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0003_worker'),
    ]

    operations = [
        migrations.AddField(
            model_name='joborder',
            name='workers',
            field=models.ManyToManyField(blank=True, help_text='Production workers assigned to this job order.', related_name='job_orders', to='production.worker'),
        ),
        migrations.AddField(
            model_name='materialissueslip',
            name='issued_to_worker',
            field=models.ForeignKey(blank=True, help_text='Worker this material is issued to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='material_issue_slips', to='production.worker'),
        ),
        migrations.AddField(
            model_name='productionprocess',
            name='worker',
            field=models.ForeignKey(blank=True, help_text='Worker performing this production operation.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_processes', to='production.worker'),
        ),
    ]
