# Generated by Django 4.2.22 on 2026-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0004_joborder_workers_materialissueslip_issued_to_worker_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dispatch',
            name='dispatch_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='finishedgoods',
            name='finished_goods_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='goodsreceiptnote',
            name='grn_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='joborder',
            name='job_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='machine',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='materialissueslip',
            name='slip_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='purchaserequisition',
            name='requisition_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='qualityinspection',
            name='inspection_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='worker_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
