# Generated by Django 4.2.22 on 2026-09-08 09:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0005_alter_dispatch_dispatch_no_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyWorkEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, help_text='Date the work was performed.')),
                ('description', models.TextField(blank=True, default='', help_text='Summary of the work done.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('job_order', models.ForeignKey(blank=True, help_text='Job order the work belongs to, if any.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='daily_work_entries', to='production.joborder')),
                ('worker', models.ForeignKey(help_text='Worker who performed the work (derived from the logged-in user).', on_delete=django.db.models.deletion.CASCADE, related_name='daily_work_entries', to='production.worker')),
            ],
            options={
                'ordering': ['-date', 'worker__user__first_name', 'worker__user__last_name'],
            },
        ),
    ]
