# Generated by Django 4.2.22 on 2026-08-04 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('sales', '0002_customer_deliverynote_salesorder_salesorderitem_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='salesreportitem',
            name='product',
        ),
        migrations.RemoveField(
            model_name='salesreportitem',
            name='report',
        ),
        migrations.AddField(
            model_name='salesorder',
            name='employee',
            field=models.ForeignKey(blank=True, help_text='Sales rep responsible for the order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.DeleteModel(
            name='SalesReport',
        ),
        migrations.DeleteModel(
            name='SalesReportItem',
        ),
    ]
