# Generated by Django 4.2.22 on 2026-08-05 05:58

from django.db import migrations, models
import django.db.models.deletion


def get_or_create_tax(Tax, rate):
    existing = Tax.objects.filter(rate=rate).first()
    if existing:
        return existing
    return Tax.objects.create(
        tax_id=f'TAX-{rate}',
        name=f'Tax {rate}%',
        rate=rate,
        status='active',
        applied_to='both',
    )


def backfill_sales_tax(apps, schema_editor):
    SalesOrderItem = apps.get_model('sales', 'SalesOrderItem')
    DeliveryNote = apps.get_model('sales', 'DeliveryNote')
    Tax = apps.get_model('finance', 'Tax')

    for model in (SalesOrderItem, DeliveryNote):
        for row in model.objects.all():
            rate = row.tax_decimal_tmp
            if rate:
                tax = get_or_create_tax(Tax, rate)
                model.objects.filter(pk=row.pk).update(tax=tax)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_tax_from_taxrate'),
        ('sales', '0003_remove_salesreportitem_product_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='deliverynote',
            old_name='tax',
            new_name='tax_decimal_tmp',
        ),
        migrations.RenameField(
            model_name='salesorderitem',
            old_name='tax',
            new_name='tax_decimal_tmp',
        ),
        migrations.AddField(
            model_name='deliverynote',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to the subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='finance.tax'),
        ),
        migrations.AddField(
            model_name='salesorderitem',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to the line amount.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_order_items', to='finance.tax'),
        ),
        migrations.RunPython(backfill_sales_tax),
        migrations.RemoveField(
            model_name='deliverynote',
            name='tax_decimal_tmp',
        ),
        migrations.RemoveField(
            model_name='salesorderitem',
            name='tax_decimal_tmp',
        ),
    ]
