# Generated by Django 4.2.22 on 2026-08-05 09:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_alter_deliverynote_tax_alter_salesorderitem_tax'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=200)),
                ('feedback', models.TextField()),
                ('date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('resolved', 'Resolved'), ('in_review', 'In Review'), ('pending', 'Pending')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='sales.customer')),
            ],
            options={
                'ordering': ['-date', '-created_at'],
            },
        ),
    ]
