# Generated by Django 4.2.22 on 2026-08-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0004_quotation_customer_quotation_delivery_date_and_more'),
        ('sales', '0005_customerfeedback'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliverynote',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales order this delivery note fulfils.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery_notes', to='sales.salesorder'),
        ),
        migrations.AddField(
            model_name='salesorder',
            name='quotation',
            field=models.ForeignKey(blank=True, help_text='Quotation that was approved to create this order.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales_orders', to='orders.quotation'),
        ),
    ]
