# Generated by Django 4.2.22 on 2026-08-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_about_contact_type_contact_visible_to_and_more'),
        ('projects', '0005_project_timesheet_task_milestone_resource_allocation'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Registered company this project is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='projects', to='contacts.company'),
        ),
    ]
