# Generated by Django 4.2.22 on 2026-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_backfill_project_company'),
    ]

    operations = [
        migrations.AlterField(
            model_name='milestone',
            name='milestone_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='project_id',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
