# Generated by Django 4.2.22 on 2026-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='role',
            field=models.CharField(choices=[('manager', 'Manager'), ('msr', 'MSR'), ('dealer', 'Dealer'), ('retailer', 'Retailer'), ('company', 'Company')], max_length=20),
        ),
    ]
