# Generated by Django 4.2.22 on 2026-07-30 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_add_2fa_email_verification_delete_account'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TwoFactorCode',
        ),
    ]
