# Generated by Django 4.2.22 on 2026-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('msr', 'MSR'), ('dealer', 'Dealer'), ('retailer', 'Retailer'), ('company', 'Company')], max_length=20),
        ),
    ]
