# Generated by Django 4.2.22 on 2026-08-05 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0003_shift_remove_department_is_active_and_more'),
        ('accounts', '0006_role_useractivitylog_loginlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.ForeignKey(blank=True, help_text='Department this employee belongs to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='settings_config.department'),
        ),
        migrations.AddField(
            model_name='user',
            name='designation',
            field=models.ForeignKey(blank=True, help_text='Designation / job title of this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='settings_config.designation'),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='user',
            name='shift',
            field=models.ForeignKey(blank=True, help_text='Work shift assigned to this employee.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employees', to='settings_config.shift'),
        ),
    ]
