# Generated by Django 4.2.22 on 2026-08-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_user_department_user_designation_user_salary_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shift',
        ),
        migrations.AddField(
            model_name='user',
            name='shift_end_time',
            field=models.TimeField(blank=True, help_text='Work shift end time for this employee.', null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='shift_start_time',
            field=models.TimeField(blank=True, help_text='Work shift start time for this employee.', null=True),
        ),
    ]
