# Generated by Django 4.2.22 on 2026-08-31 05:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_product_tax_percentage_product_tax'),
        ('settings_config', '0004_remove_city_state_delete_shift_delete_city_and_more'),
        ('accounts', '0009_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('msr', 'MSR'), ('dealer', 'Dealer'), ('retailer', 'Retailer'), ('company', 'Company'), ('hr', 'HR'), ('accountant', 'Accountant'), ('sales_executive', 'Sales Executive'), ('marketing_executive', 'Marketing Executive'), ('developer', 'Developer'), ('support_executive', 'Support Executive'), ('operation_executive', 'Operations Executive'), ('project_manager', 'Project Manager'), ('quality_analyst', 'Quality Analyst'), ('designer', 'Designer')], max_length=20),
        ),
        migrations.CreateModel(
            name='DesignDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('design_no', models.CharField(blank=True, max_length=20, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('document_type', models.CharField(choices=[('cad', 'CAD Drawing'), ('technical', 'Technical Drawing'), ('mockup', 'Mockup'), ('flow', 'Flow Diagram'), ('other', 'Other')], default='other', max_length=20)),
                ('version', models.CharField(default='1.0', max_length=20)),
                ('file', models.FileField(upload_to='designs/')),
                ('thumbnail', models.ImageField(blank=True, null=True, upload_to='designs/thumbnails/')),
                ('is_public', models.BooleanField(default=False, help_text='If true, visible to all departments.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('designer', models.ForeignKey(blank=True, help_text='Designer who uploaded this design.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_documents', to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(blank=True, help_text='Optional product this design is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_documents', to='products.product')),
                ('visible_to', models.ManyToManyField(blank=True, help_text='Departments allowed to view this design.', related_name='visible_designs', to='settings_config.department')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
