# Generated by Django 4.2.22 on 2026-08-31 07:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('production', '0002_productionstage'),
        ('accounts', '0010_alter_user_role_designdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designdocument',
            name='product',
        ),
        migrations.AddField(
            model_name='designdocument',
            name='machine',
            field=models.ForeignKey(blank=True, help_text='Production machine / equipment this design is for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='design_documents', to='production.machine'),
        ),
    ]
