# Generated by Django 4.2.22 on 2026-08-31 07:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_remove_designdocument_product_designdocument_machine'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='designdocument',
            name='machine',
        ),
    ]
