# Generated by Django 4.2.22 on 2026-08-31 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_remove_designdocument_machine'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('super_admin', 'Super Admin'), ('manager', 'Manager'), ('msr', 'MSR'), ('dealer', 'Dealer'), ('retailer', 'Retailer'), ('company', 'Company'), ('hr', 'HR'), ('accountant', 'Accountant'), ('sales_executive', 'Sales Executive'), ('marketing_executive', 'Marketing Executive'), ('developer', 'Developer'), ('support_executive', 'Support Executive'), ('operation_executive', 'Operations Executive'), ('project_manager', 'Project Manager'), ('quality_analyst', 'Quality Analyst'), ('designer', 'Designer'), ('production_worker', 'Production Worker')], max_length=20),
        ),
    ]
