# Generated by Django 4.2.22 on 2026-09-07 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='designdocument',
            name='design_no',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
