# Generated by Django 4.2.22 on 2026-09-08 04:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0014_alter_designdocument_design_no'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='user',
            constraint=models.UniqueConstraint(condition=models.Q(('email__gt', '')), fields=('email',), name='unique_user_email'),
        ),
    ]
