# Generated by Django 4.2.22 on 2026-07-29 05:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='leave',
            name='assigned_approver',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_approvals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='LeaveApprovalWorkflow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=1)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('approver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assigned_approvals', to=settings.AUTH_USER_MODEL)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='approval_workflows', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['employee', 'priority'],
                'unique_together': {('employee', 'priority')},
            },
        ),
    ]
