# Generated by Django 4.2.22 on 2026-07-29 09:33

import apps.leaves.models
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leaves', '0003_leaveallocation'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='leaveallocation',
            name='year',
            field=models.IntegerField(default=apps.leaves.models.current_year),
        ),
        migrations.AlterUniqueTogether(
            name='leaveallocation',
            unique_together={('employee', 'leave_type', 'year')},
        ),
    ]
