# Generated by Django 4.2.22 on 2026-07-29 12:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0001_initial'),
        ('masters', '0002_currency_industry_source_taxrate'),
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='address',
        ),
        migrations.RemoveField(
            model_name='company',
            name='pin_code',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='address',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='notes',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='pin_code',
        ),
        migrations.AddField(
            model_name='company',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='companies/'),
        ),
        migrations.AddField(
            model_name='company',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='companies_list', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='company',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='masters.currency'),
        ),
        migrations.AddField(
            model_name='company',
            name='deals',
            field=models.ManyToManyField(blank=True, related_name='related_companies', to='pipeline.deal'),
        ),
        migrations.AddField(
            model_name='company',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='company',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='company',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='reviews',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='company',
            name='skype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='company',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='company',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='company',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='company',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='company',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='contacts/'),
        ),
        migrations.AddField(
            model_name='contact',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='masters.currency'),
        ),
        migrations.AddField(
            model_name='contact',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='deals',
            field=models.ManyToManyField(blank=True, related_name='related_contacts', to='pipeline.deal'),
        ),
        migrations.AddField(
            model_name='contact',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='contact',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='first_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='masters.industry'),
        ),
        migrations.AddField(
            model_name='contact',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='contact',
            name='last_name',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='reviews',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='contact',
            name='skype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='contact',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='contact',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='public', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='contact',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='company',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='masters.industry'),
        ),
        migrations.AlterField(
            model_name='company',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='companies', to='masters.source'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contact_list', to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='contact',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contacts', to='masters.source'),
        ),
    ]
