# Generated by Django 4.2.22 on 2026-08-05 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_contactmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.CharField(choices=[('person', 'Person'), ('business', 'Business')], default='person', help_text='Person or business contact.', max_length=10),
        ),
        migrations.AddField(
            model_name='contact',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='People who can see this contact when visibility is "selected".', related_name='visible_contacts', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='contact',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('selected', 'Selected')], default='public', max_length=10),
        ),
    ]
