# Generated by Django 4.2.22 on 2026-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0006_alter_budget_budget_id_alter_cashflow_ref_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchasetax',
            name='bill_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
