# Generated by Django 4.2.30 on 2026-09-10 06:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("hytech_customers", "0001_initial"),
        ("hytech_services", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Reminder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "reminder_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "reminder_type",
                    models.CharField(default="SERVICE_READY", max_length=50),
                ),
                ("subject", models.CharField(max_length=200)),
                ("due_date", models.DateField()),
                ("reminder_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("message_template", models.TextField(blank=True, null=True)),
                (
                    "follow_up_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("DONE", "Done"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                ("last_contact_date", models.DateTimeField(blank=True, null=True)),
                ("customer_response", models.TextField(blank=True, null=True)),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reminders",
                        to="hytech_customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="reminders",
                        to="hytech_services.baseservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="PendingWork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "pending_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("pending_since", models.DateField(default=django.utils.timezone.now)),
                ("expected_date", models.DateField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                        ],
                        default="MEDIUM",
                        max_length=20,
                    ),
                ),
                ("pending_reason", models.TextField()),
                ("documents_pending", models.TextField(blank=True, null=True)),
                ("next_action", models.TextField(blank=True, null=True)),
                (
                    "work_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("BLOCKED", "Blocked"),
                            ("COMPLETED", "Completed"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("follow_up_date", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_pending_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_pending_works",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="pending_works",
                        to="hytech_customers.customer",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_works",
                        to="hytech_services.baseservice",
                    ),
                ),
                (
                    "service_visit",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="pending_works",
                        to="hytech_customers.servicevisit",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FollowUp",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("contact_date", models.CharField(max_length=100)),
                ("customer_response", models.TextField()),
                ("next_follow_up", models.DateField(blank=True, null=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "contacted_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="logged_follow_ups",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "reminder",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="follow_ups",
                        to="hytech_operations.reminder",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Application",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "application_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                ("applicant_name", models.CharField(blank=True, max_length=200)),
                ("applicant_mobile", models.CharField(blank=True, max_length=20)),
                ("category", models.CharField(blank=True, max_length=50, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "Draft"),
                            ("DOCUMENT_CHECK", "Document Check"),
                            ("READY_TO_SUBMIT", "Ready to Submit"),
                            ("SUBMITTED", "Submitted"),
                            ("GOVERNMENT_PROCESSING", "Government Processing"),
                            ("PENDING", "Pending"),
                            ("ACTION_REQUIRED", "Action Required"),
                            ("APPROVED", "Approved"),
                            ("COMPLETED", "Completed"),
                            ("REJECTED", "Rejected"),
                            ("CANCELLED", "Cancelled"),
                            ("SCRUTINY", "Scrutiny"),
                            ("DOCS_PENDING", "Documents Pending"),
                        ],
                        default="DRAFT",
                        max_length=40,
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("HIGH", "High"),
                            ("MEDIUM", "Medium"),
                            ("LOW", "Low"),
                            ("NORMAL", "Normal"),
                            ("URGENT", "Urgent"),
                        ],
                        default="NORMAL",
                        max_length=20,
                    ),
                ),
                (
                    "government_app_no",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "government_portal_url",
                    models.URLField(blank=True, max_length=500, null=True),
                ),
                (
                    "govt_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "service_charge",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "total_fee",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("payment_status", models.CharField(default="PAID", max_length=20)),
                (
                    "payment_mode",
                    models.CharField(blank=True, max_length=30, null=True),
                ),
                ("receipt_no", models.CharField(blank=True, max_length=50, null=True)),
                ("expected_date", models.DateField(blank=True, null=True)),
                ("sla_days", models.PositiveIntegerField(default=7)),
                ("documents", models.JSONField(blank=True, default=list)),
                ("form_data", models.JSONField(blank=True, default=dict)),
                ("timeline", models.JSONField(blank=True, default=list)),
                ("notes", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assigned_staff",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="created_applications",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="applications",
                        to="hytech_customers.customer",
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="hytech_customers.familymember",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="hytech_services.baseservice",
                    ),
                ),
                (
                    "sub_service",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="applications",
                        to="hytech_services.subservice",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
    ]
