# Generated by Django 4.2.30 on 2026-09-10 10:55

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("hytech_operations", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pendingwork",
            name="pending_since",
            field=models.DateField(default=django.utils.timezone.localdate),
        ),
    ]
