# Generated by Django 4.2.22 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='payment_method',
            field=models.CharField(choices=[('cash', 'Cash'), ('cheque', 'Cheque'), ('bank_transfer', 'Bank Transfer'), ('online', 'Online'), ('other', 'Other')], default='cash', max_length=20),
        ),
        migrations.AddField(
            model_name='invoice',
            name='terms_conditions',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='invoice',
            name='transaction_id',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
