# Generated by Django 4.2.22 on 2026-08-06 06:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_customerfeedback'),
        ('invoices', '0003_remove_invoice_tax_percentage_invoice_tax'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='delivery_note',
            field=models.ForeignKey(blank=True, help_text='Delivery note this invoice was raised from.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.deliverynote'),
        ),
        migrations.AddField(
            model_name='invoice',
            name='sales_order',
            field=models.ForeignKey(blank=True, help_text='Sales order this invoice bills for.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='sales.salesorder'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='invoice_number',
            field=models.CharField(blank=True, max_length=50, unique=True),
        ),
    ]
