# Generated by Django 4.2.22 on 2026-08-07 10:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_contact_about_contact_type_contact_visible_to_and_more'),
        ('invoices', '0004_invoice_delivery_note_invoice_sales_order_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='company',
            field=models.ForeignKey(blank=True, help_text='Registered company this invoice is connected to.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invoices', to='contacts.company'),
        ),
    ]
