# Generated by Django 4.2.22 on 2026-07-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0002_remove_visit_mechanic_alter_visit_visit_type'),
        ('masters', '0002_currency_industry_source_taxrate'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Mechanic',
        ),
    ]
