# Generated by Django 4.2.30 on 2026-09-09 08:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HolidayItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('title_gu', models.CharField(max_length=200)),
                ('date', models.DateField()),
                ('day', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[('GOVERNMENT', 'Government Holiday'), ('REGIONAL', 'Regional Holiday'), ('NATIONAL', 'National Holiday')], default='GOVERNMENT', max_length=30)),
                ('description', models.TextField(blank=True, null=True)),
            ],
            options={
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='LeaveRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('leave_type', models.CharField(choices=[('CASUAL', 'Casual Leave'), ('SICK', 'Sick Leave'), ('PAID', 'Paid Leave'), ('UNPAID', 'Unpaid Leave')], default='CASUAL', max_length=30)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('days_count', models.PositiveIntegerField(default=1)),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('APPROVED', 'Approved'), ('PENDING', 'Pending'), ('REJECTED', 'Rejected')], default='PENDING', max_length=30)),
                ('applied_at', models.DateTimeField(auto_now_add=True)),
                ('approved_by', models.CharField(blank=True, max_length=200, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hytech_leaves', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-applied_at'],
            },
        ),
        migrations.CreateModel(
            name='LeaveBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('casual_total', models.IntegerField(default=12)),
                ('casual_used', models.IntegerField(default=0)),
                ('sick_total', models.IntegerField(default=7)),
                ('sick_used', models.IntegerField(default=0)),
                ('paid_total', models.IntegerField(default=5)),
                ('paid_used', models.IntegerField(default=0)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='hytech_leave_balance', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='AttendanceRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.now)),
                ('day_name', models.CharField(blank=True, max_length=50)),
                ('in_time', models.CharField(blank=True, max_length=50, null=True)),
                ('out_time', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PRESENT', 'Present'), ('ABSENT', 'Absent'), ('HALF_DAY', 'Half Day'), ('HOLIDAY', 'Holiday'), ('LEAVE', 'Leave')], default='PRESENT', max_length=30)),
                ('work_hours', models.FloatField(default=0.0)),
                ('notes', models.TextField(blank=True, null=True)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hytech_attendances', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-date', 'employee'],
                'unique_together': {('employee', 'date')},
            },
        ),
    ]
