# Generated by Django 5.1.1 on 2026-09-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hytech_hrms', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HRAttendanceSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grace_period_minutes', models.IntegerField(default=15)),
                ('grace_period_label', models.CharField(default='15 Minutes', max_length=50)),
                ('half_day_cutoff_time', models.CharField(default='01:30 PM', max_length=50)),
                ('shift_start_time', models.CharField(default='09:30 AM', max_length=50)),
                ('shift_end_time', models.CharField(default='06:30 PM', max_length=50)),
                ('standard_work_hours', models.FloatField(default=8.0)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Attendance Setting',
                'verbose_name_plural': 'HR Attendance Settings',
            },
        ),
        migrations.CreateModel(
            name='HRCompanySetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organization_name', models.CharField(default='HY-TECH CITIZEN SERVICES & COMPUTER HUB', max_length=255)),
                ('opening_time', models.CharField(default='09:00 AM', max_length=50)),
                ('closing_time', models.CharField(default='07:00 PM', max_length=50)),
                ('contact_email', models.EmailField(blank=True, default='contact@hytech.com', max_length=100)),
                ('contact_phone', models.CharField(blank=True, default='+91 98765 43210', max_length=50)),
                ('address', models.TextField(blank=True, default='Opp. Bus Station, Main Road, Gujarat')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Company Setting',
                'verbose_name_plural': 'HR Company Settings',
            },
        ),
        migrations.CreateModel(
            name='HRLeaveSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('annual_casual_leave', models.IntegerField(default=12)),
                ('annual_sick_leave', models.IntegerField(default=6)),
                ('annual_paid_leave', models.IntegerField(default=18)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Leave Setting',
                'verbose_name_plural': 'HR Leave Settings',
            },
        ),
        migrations.CreateModel(
            name='HRNotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('whatsapp_daily_punch_summary', models.BooleanField(default=True)),
                ('sms_leave_approval', models.BooleanField(default=True)),
                ('email_leave_notifications', models.BooleanField(default=False)),
                ('admin_whatsapp_number', models.CharField(blank=True, default='', max_length=50)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Notification Setting',
                'verbose_name_plural': 'HR Notification Settings',
            },
        ),
        migrations.CreateModel(
            name='HRRolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('ADMIN', 'Administrator'), ('STAFF', 'Staff Operator'), ('HR', 'HR Manager')], max_length=50, unique=True)),
                ('display_name', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('can_manage_employees', models.BooleanField(default=False)),
                ('can_view_attendance', models.BooleanField(default=True)),
                ('can_mark_attendance', models.BooleanField(default=True)),
                ('can_approve_leaves', models.BooleanField(default=False)),
                ('can_manage_payroll', models.BooleanField(default=False)),
                ('can_view_reports', models.BooleanField(default=False)),
                ('can_manage_settings', models.BooleanField(default=False)),
                ('can_process_services', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'HR Role Permission',
                'verbose_name_plural': 'HR Role Permissions',
                'ordering': ['role'],
            },
        ),
    ]
