# Generated by Django 4.2.22 on 2026-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('settings_config', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Country',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(blank=True, help_text='Country dial code or ISO code', max_length=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': 'Countries',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='EmailSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mail_driver', models.CharField(choices=[('php_mail', 'PHP Mail'), ('smtp', 'SMTP'), ('mail', 'Mail')], default='smtp', max_length=20)),
                ('host', models.CharField(blank=True, max_length=200)),
                ('port', models.PositiveIntegerField(default=587)),
                ('encryption', models.CharField(blank=True, default='tls', max_length=20)),
                ('username', models.CharField(blank=True, max_length=200)),
                ('password', models.CharField(blank=True, max_length=500)),
                ('from_email', models.EmailField(blank=True, max_length=254)),
                ('from_name', models.CharField(blank=True, max_length=200)),
            ],
            options={
                'verbose_name': 'Email Setting',
            },
        ),
        migrations.CreateModel(
            name='NotificationSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(choices=[('email', 'Email'), ('sms', 'SMS'), ('push', 'Push'), ('in_app', 'In-App')], max_length=20, unique=True)),
                ('email_enabled', models.BooleanField(default=True)),
                ('sms_enabled', models.BooleanField(default=False)),
                ('push_enabled', models.BooleanField(default=True)),
                ('in_app_enabled', models.BooleanField(default=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['module'],
            },
        ),
        migrations.CreateModel(
            name='SmsGateway',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('api_key', models.CharField(blank=True, max_length=500)),
                ('api_secret', models.CharField(blank=True, max_length=500)),
                ('sender_id', models.CharField(blank=True, max_length=100)),
                ('is_default', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-is_default', 'name'],
            },
        ),
        migrations.CreateModel(
            name='StorageSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('driver', models.CharField(choices=[('local', 'Local'), ('aws', 'AWS S3')], default='local', max_length=20)),
                ('aws_access_key', models.CharField(blank=True, max_length=500)),
                ('aws_secret_key', models.CharField(blank=True, max_length=500)),
                ('bucket', models.CharField(blank=True, max_length=200)),
                ('region', models.CharField(blank=True, max_length=100)),
                ('base_url', models.URLField(blank=True)),
            ],
            options={
                'verbose_name': 'Storage Setting',
            },
        ),
        migrations.CreateModel(
            name='SystemUpdate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_key', models.CharField(blank=True, max_length=500)),
                ('version', models.CharField(default='1.0.0', max_length=20)),
                ('is_updated', models.BooleanField(default=False)),
                ('last_checked_at', models.DateTimeField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'System Update',
            },
        ),
    ]
