# Generated by Django 4.2.22 on 2026-07-29 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailcampaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign_attachments/'),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='campaign_type',
            field=models.CharField(choices=[('regular', 'Regular'), ('automated', 'Automated'), ('triggered', 'Triggered')], default='regular', max_length=20),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='period',
            field=models.CharField(blank=True, choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], max_length=10),
        ),
        migrations.AddField(
            model_name='emailcampaign',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
