# Generated by Django 4.2.22 on 2026-07-31 05:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('email_marketing', '0002_emailcampaign_attachment_emailcampaign_campaign_type_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriberList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('total_contacts', models.PositiveIntegerField(default=0)),
                ('active_subscribers', models.PositiveIntegerField(default=0)),
                ('bounce_rate', models.DecimalField(decimal_places=2, default=0, help_text='Bounce rate in %', max_digits=5)),
                ('last_campaign_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
