# Generated by Django 4.2.30 on 2026-09-10 06:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("admin", "Admin"),
                            ("staff", "Staff"),
                            ("hr", "HR"),
                            ("customer", "Customer"),
                        ],
                        max_length=20,
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=15)),
                ("date_of_birth", models.DateField(blank=True, null=True)),
            ],
            options={
                "verbose_name_plural": "Users",
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "family_id",
                    models.CharField(
                        blank=True, db_index=True, max_length=50, unique=True
                    ),
                ),
                (
                    "registration_date",
                    models.DateField(default=django.utils.timezone.localdate),
                ),
                ("head_of_family", models.CharField(max_length=200)),
                ("mobile_number", models.CharField(db_index=True, max_length=20)),
                (
                    "whatsapp_number",
                    models.CharField(blank=True, max_length=20, null=True),
                ),
                ("family_member_count", models.PositiveIntegerField(default=1)),
                ("village_city", models.CharField(blank=True, max_length=200)),
                ("birth_date", models.DateField(blank=True, null=True)),
                (
                    "referral_family_id",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("document_consent", models.BooleanField(default=True)),
                ("current_points", models.IntegerField(default=0)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                ("total_visits", models.PositiveIntegerField(default=0)),
                ("last_visit", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("notes", models.TextField(blank=True, null=True)),
                ("digital_card_sent", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="CustomerDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.CharField(blank=True, max_length=50)),
                ("member_name", models.CharField(blank=True, max_length=200)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("AADHAR", "Aadhaar Card"),
                            ("VOTER_ID", "Voter ID / Election Card"),
                            ("PAN", "PAN Card"),
                            ("RATION_CARD", "Ration Card"),
                            ("BIRTH_CERTIFICATE", "Birth Certificate"),
                            ("CASTE_CERTIFICATE", "Caste Certificate"),
                            ("INCOME_CERTIFICATE", "Income Certificate"),
                            ("DRIVING_LICENSE", "Driving License"),
                            ("PHOTO", "Passport Photo"),
                            ("OTHER", "Other Document"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_name", models.CharField(max_length=255)),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="customer_documents/"
                    ),
                ),
                ("description", models.TextField(blank=True, null=True)),
                ("is_verified", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="FamilyMember",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("family_id", models.CharField(blank=True, max_length=50)),
                ("name", models.CharField(max_length=200)),
                (
                    "relationship",
                    models.CharField(
                        choices=[
                            ("HEAD", "Head of Family"),
                            ("SELF", "Self"),
                            ("WIFE", "Wife"),
                            ("HUSBAND", "Husband"),
                            ("SON", "Son"),
                            ("DAUGHTER", "Daughter"),
                            ("FATHER", "Father"),
                            ("MOTHER", "Mother"),
                            ("BROTHER", "Brother"),
                            ("SISTER", "Sister"),
                            ("OTHER", "Other"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "gender",
                    models.CharField(
                        choices=[
                            ("MALE", "Male"),
                            ("FEMALE", "Female"),
                            ("OTHER", "Other"),
                        ],
                        default="MALE",
                        max_length=20,
                    ),
                ),
                ("mobile_number", models.CharField(blank=True, max_length=20)),
                ("birth_date", models.DateField(blank=True, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "ordering": ["id"],
            },
        ),
        migrations.CreateModel(
            name="ServiceVisit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "visit_no",
                    models.CharField(db_index=True, max_length=50, unique=True),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pending"),
                            ("IN_PROGRESS", "In Progress"),
                            ("COMPLETED", "Completed"),
                            ("CANCELLED", "Cancelled"),
                        ],
                        default="PENDING",
                        max_length=30,
                    ),
                ),
                ("visit_date", models.DateField(default=django.utils.timezone.now)),
                ("remarks", models.TextField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "checked_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="checked_visits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="service_visits",
                        to="hytech_customers.customer",
                    ),
                ),
                (
                    "family_member",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="service_visits",
                        to="hytech_customers.familymember",
                    ),
                ),
            ],
            options={
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VisitDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("document_type", models.CharField(max_length=50)),
                ("document_name", models.CharField(max_length=255)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("AVAILABLE", "Available"),
                            ("NOT_AVAILABLE", "Not Available"),
                        ],
                        default="NOT_AVAILABLE",
                        max_length=30,
                    ),
                ),
                (
                    "document_file",
                    models.FileField(
                        blank=True, null=True, upload_to="visit_documents/"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "visit",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="hytech_customers.servicevisit",
                    ),
                ),
            ],
            options={
                "ordering": ["id"],
            },
        ),
    ]
