# Generated by Django 4.2.30 on 2026-09-09 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hytech_customers', '0001_initial'),
        ('hytech_services', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicevisit',
            name='service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='hytech_services.baseservice'),
        ),
        migrations.AddField(
            model_name='servicevisit',
            name='sub_service',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='hytech_services.subservice'),
        ),
        migrations.AddField(
            model_name='familymember',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='hytech_customers.customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='hytech_customers.customer'),
        ),
        migrations.AddField(
            model_name='customerdocument',
            name='family_member',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='documents', to='hytech_customers.familymember'),
        ),
    ]
