# Generated by Django 4.2.30 on 2026-09-10 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hytech_customers", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="joining_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, unique=True),
        ),
    ]
