# Generated by Django 4.2.30 on 2026-09-09 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hytech_customers', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='password',
            field=models.CharField(blank=True, default='', help_text='Encrypted password for Citizen Portal login', max_length=128),
        ),
    ]
