# Generated by Django 4.2.30 on 2026-09-10 06:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("hytech_customers", "0003_user_joining_date_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="joining_date",
        ),
    ]
