# Generated by Django 4.2.22 on 2026-09-07 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_due_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='ticket_id',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
