from django.urls import path
from . import views

urlpatterns = [
    path('categories/', views.ProductCategoryListCreateView.as_view(), name='product-category-list'),
    path('categories/<int:pk>/', views.ProductCategoryDetailView.as_view(), name='product-category-detail'),
    path('', views.ProductListCreateView.as_view(), name='product-list'),
    path('<int:pk>/', views.ProductDetailView.as_view(), name='product-detail'),
    path('<int:pk>/toggle-active/', views.ProductToggleActiveView.as_view(), name='product-toggle-active'),
    path('catalogue/', views.ProductCatalogueView.as_view(), name='product-catalogue'),
    path('tour-plans/', views.TourPlanListCreateView.as_view(), name='tour-plan-list'),
    path('tour-plans/<int:pk>/', views.TourPlanDetailView.as_view(), name='tour-plan-detail'),
    path('tour-plans/<int:pk>/toggle-active/', views.TourPlanToggleActiveView.as_view(), name='tour-plan-toggle'),
    path('policies/', views.PolicyListCreateView.as_view(), name='policy-list'),
    path('policies/<int:pk>/', views.PolicyDetailView.as_view(), name='policy-detail'),
    path('policies/<int:pk>/toggle-active/', views.PolicyToggleActiveView.as_view(), name='policy-toggle'),
    path('inventories/', views.InventoryListCreateView.as_view(), name='inventory-list'),
    path('inventories/<int:pk>/', views.InventoryDetailView.as_view(), name='inventory-detail'),
    path('inventories/<int:pk>/toggle-active/', views.InventoryToggleActiveView.as_view(), name='inventory-toggle'),
    path('stock-adjustments/', views.StockAdjustmentListCreateView.as_view(), name='stock-adjustment-list'),
    path('stock-adjustments/<int:pk>/', views.StockAdjustmentDetailView.as_view(), name='stock-adjustment-detail'),
    path('stock-transfers/', views.StockTransferListCreateView.as_view(), name='stock-transfer-list'),
    path('stock-transfers/<int:pk>/', views.StockTransferDetailView.as_view(), name='stock-transfer-detail'),
    path('warehouses/', views.WarehouseListCreateView.as_view(), name='warehouse-list'),
    path('warehouses/<int:pk>/', views.WarehouseDetailView.as_view(), name='warehouse-detail'),
    path('warehouses/<int:pk>/toggle-active/', views.WarehouseToggleActiveView.as_view(), name='warehouse-toggle'),
    path('suppliers/', views.SupplierListCreateView.as_view(), name='supplier-list'),
    path('suppliers/<int:pk>/', views.SupplierDetailView.as_view(), name='supplier-detail'),
    path('suppliers/<int:pk>/toggle-active/', views.SupplierToggleActiveView.as_view(), name='supplier-toggle'),
]
