# Generated by Django 4.2.22 on 2026-07-30 05:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('sms', 'SMS'), ('social', 'Social'), ('email', 'Email')], max_length=20)),
                ('name', models.CharField(max_length=200)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('title', models.CharField(blank=True, default='', max_length=500)),
                ('message', models.TextField(blank=True, default='')),
                ('content', models.TextField(blank=True, default='')),
                ('recipient_filter', models.JSONField(blank=True, default=dict)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('scheduled', 'Scheduled'), ('sending', 'Sending'), ('sent', 'Sent'), ('completed', 'Completed'), ('archived', 'Archived')], default='draft', max_length=20)),
                ('scheduled_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('stats_sent_count', models.IntegerField(default=0)),
                ('stats_opened_count', models.IntegerField(default=0)),
                ('stats_clicked_count', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CampaignAttachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(upload_to='campaign_attachments/')),
                ('name', models.CharField(max_length=200)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='marketing.campaign')),
            ],
        ),
    ]
