# Generated by Django 4.2.22 on 2026-08-03 04:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='attachment',
            field=models.FileField(blank=True, null=True, upload_to='campaign_attachments/'),
        ),
        migrations.AddField(
            model_name='campaign',
            name='currency',
            field=models.CharField(blank=True, choices=[('usd', 'Dollar'), ('eur', 'Euro'), ('gbp', 'Pound'), ('inr', 'Rupee')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='deal_value',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='campaign',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='campaign',
            name='period',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('weekly', 'Weekly'), ('monthly', 'Monthly')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='campaign',
            name='period_value',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='campaign',
            name='target_audience',
            field=models.TextField(blank=True, default=''),
        ),
    ]
