# Generated by Django 4.2.22 on 2026-08-03 04:41

import json

from django.db import migrations, models


def convert_target_audience(apps, schema_editor):
    Campaign = apps.get_model('marketing', 'Campaign')
    for campaign in Campaign.objects.all():
        value = campaign.target_audience
        if value is None or value == '':
            campaign.target_audience = '[]'
        elif isinstance(value, str):
            parts = [part.strip() for part in value.split(',') if part.strip()]
            campaign.target_audience = json.dumps(parts)
        else:
            continue
        campaign.save(update_fields=['target_audience'])


def convert_target_audience_back(apps, schema_editor):
    Campaign = apps.get_model('marketing', 'Campaign')
    for campaign in Campaign.objects.all():
        value = campaign.target_audience
        if isinstance(value, list):
            campaign.target_audience = ', '.join(value)
            campaign.save(update_fields=['target_audience'])


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0002_campaign_attachment_campaign_currency_and_more'),
    ]

    operations = [
        migrations.RunPython(convert_target_audience, convert_target_audience_back),
        migrations.AlterField(
            model_name='campaign',
            name='target_audience',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
