# Generated by Django 4.2.22 on 2026-08-05 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0003_alter_campaign_target_audience'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=20),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='target_audience',
            field=models.JSONField(blank=True, default=list, help_text='List of audience groups: customers, leads, subscribers.'),
        ),
        migrations.AlterField(
            model_name='campaign',
            name='type',
            field=models.CharField(choices=[('basic', 'Basic'), ('pro', 'Pro'), ('enterprise', 'Enterprise')], default='basic', max_length=20),
        ),
    ]
