# Generated by Django 4.2.22 on 2026-08-06 04:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketing', '0004_alter_campaign_status_alter_campaign_target_audience_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='campaign',
            name='status',
            field=models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive'), ('ending_soon', 'Ending Soon'), ('completed', 'Completed'), ('archived', 'Archived')], default='active', max_length=20),
        ),
    ]
