# Generated by Django 4.2.22 on 2026-07-29 12:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('masters', '0002_currency_industry_source_taxrate'),
        ('projects', '0002_project_price_project_project_timing_and_more'),
        ('contacts', '0002_remove_company_address_remove_company_pin_code_and_more'),
        ('pipeline', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='deal',
            name='assignees',
            field=models.ManyToManyField(blank=True, related_name='assigned_deals', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='deal',
            name='due_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='follow_up_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deal',
            name='period',
            field=models.CharField(blank=True, choices=[('days', 'Days'), ('month', 'Month')], max_length=10),
        ),
        migrations.AddField(
            model_name='deal',
            name='period_value',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='deal',
            name='projects',
            field=models.ManyToManyField(blank=True, related_name='deals', to='projects.project'),
        ),
        migrations.AddField(
            model_name='deal',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='masters.source'),
        ),
        migrations.AddField(
            model_name='lead',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to='leads/'),
        ),
        migrations.AddField(
            model_name='lead',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='contacts',
            field=models.ManyToManyField(blank=True, related_name='leads', to='contacts.contact'),
        ),
        migrations.AddField(
            model_name='lead',
            name='country',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='email_opt_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='lead',
            name='facebook',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='fax',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='instagram',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='language',
            field=models.CharField(blank=True, default='English', max_length=50),
        ),
        migrations.AddField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('person', 'Person'), ('company', 'Company')], default='person', max_length=10),
        ),
        migrations.AddField(
            model_name='lead',
            name='linkedin',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='phone_2',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='reviews',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AddField(
            model_name='lead',
            name='skype',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='state',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='street_address',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='lead',
            name='twitter',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='website',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='lead',
            name='whatsapp',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='zipcode',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AlterField(
            model_name='deal',
            name='company',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_companies', to='contacts.company'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='contact',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deal_contacts', to='contacts.contact'),
        ),
        migrations.AlterField(
            model_name='deal',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='currency',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masters.currency'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='industry',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masters.industry'),
        ),
        migrations.AlterField(
            model_name='lead',
            name='source',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leads', to='masters.source'),
        ),
    ]
