# Generated by Django 4.2.22 on 2026-07-31 04:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0002_deal_assignees_deal_due_date_deal_follow_up_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pipelinestage',
            options={},
        ),
        migrations.RemoveField(
            model_name='deal',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='pipelinestage',
            name='order',
        ),
    ]
