# Generated by Django 4.2.22 on 2026-07-31 05:42

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('contacts', '0004_contactmessage'),
        ('pipeline', '0003_alter_pipelinestage_options_remove_deal_currency_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pipeline',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('stages', models.ManyToManyField(blank=True, related_name='pipelines', to='pipeline.pipelinestage')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Opportunity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opportunity_id', models.CharField(blank=True, max_length=50, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('account', models.CharField(blank=True, max_length=200)),
                ('expected_value', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
                ('stage', models.CharField(choices=[('qualification', 'Qualification'), ('needs_analysis', 'Needs Analysis'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('won', 'Won'), ('lost', 'Lost')], default='qualification', max_length=20)),
                ('probability', models.IntegerField(default=0, help_text='Probability %')),
                ('expected_close_date', models.DateField(blank=True, null=True)),
                ('status', models.CharField(choices=[('open', 'Open'), ('won', 'Won'), ('lost', 'Lost')], default='open', max_length=10)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='opportunities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('activity_type', models.CharField(choices=[('call', 'Call'), ('mail', 'Mail'), ('meeting', 'Meeting'), ('task', 'Task')], max_length=20)),
                ('due_date', models.DateField(blank=True, null=True)),
                ('due_time', models.TimeField(blank=True, null=True)),
                ('reminder', models.DateTimeField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('companies', models.ManyToManyField(blank=True, related_name='activities_linked', to='contacts.company')),
                ('contacts', models.ManyToManyField(blank=True, related_name='activities_linked', to='contacts.contact')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_activities', to=settings.AUTH_USER_MODEL)),
                ('deals', models.ManyToManyField(blank=True, related_name='activities_linked', to='pipeline.deal')),
                ('guests', models.ManyToManyField(blank=True, related_name='activity_guests', to=settings.AUTH_USER_MODEL)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='activities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='deal',
            name='pipeline',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deals', to='pipeline.pipeline'),
        ),
    ]
