# Generated by Django 4.2.22 on 2026-08-05 09:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('pipeline', '0004_pipeline_opportunity_activity_deal_pipeline'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deal',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='lead',
            name='name',
        ),
        migrations.AddField(
            model_name='deal',
            name='progress',
            field=models.CharField(choices=[('qualification', 'Qualification'), ('demo', 'Demo'), ('proposal', 'Proposal'), ('negotiation', 'Negotiation'), ('closed', 'Closed'), ('won', 'Won')], default='qualification', help_text='Deal progress stage.', max_length=20),
        ),
        migrations.AddField(
            model_name='lead',
            name='first_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='last_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='lead',
            name='visible_to',
            field=models.ManyToManyField(blank=True, help_text='People who can see this lead when visibility is "selected".', related_name='visible_leads', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pipeline',
            name='action',
            field=models.CharField(choices=[('all', 'All'), ('person', 'Person'), ('selected', 'Selected')], default='all', help_text='Who this pipeline applies to: everyone, a person, or selected people.', max_length=10),
        ),
        migrations.AlterField(
            model_name='deal',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('closed', 'Closed')], default='open', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='lead_type',
            field=models.CharField(choices=[('person', 'Person'), ('organization', 'Organization')], default='person', max_length=20),
        ),
        migrations.AlterField(
            model_name='lead',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private'), ('selected', 'Selected')], default='public', max_length=10),
        ),
    ]
