# Generated by Django 4.2.22 on 2026-08-06 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pipeline', '0005_remove_deal_stage_remove_lead_name_deal_progress_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='product_requirement',
            field=models.TextField(blank=True, help_text='Product or service the customer is enquiring about.'),
        ),
        migrations.AddField(
            model_name='lead',
            name='quantity',
            field=models.PositiveIntegerField(blank=True, help_text='Quantity of product enquired.', null=True),
        ),
    ]
