# Generated by Django 4.2.30 on 2026-09-11 04:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Payroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payroll_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                (
                    "payroll_month",
                    models.CharField(
                        help_text="Payroll month in YYYY-MM format.", max_length=7
                    ),
                ),
                (
                    "basic_pay",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "hra",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="House Rent Allowance (20% of basic pay).",
                        max_digits=12,
                    ),
                ),
                (
                    "allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "pf",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Provident Fund deduction.",
                        max_digits=12,
                    ),
                ),
                (
                    "net_monthly",
                    models.DecimalField(
                        decimal_places=2,
                        default=0,
                        help_text="Net monthly = basic + HRA + allowances - PF.",
                        max_digits=12,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("PENDING", "Pending"), ("PAID", "Paid")],
                        default="PENDING",
                        max_length=10,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "employee",
                    models.ForeignKey(
                        help_text="Employee this payroll belongs to.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payrolls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "Payrolls",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="Expense",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "expense_no",
                    models.CharField(editable=False, max_length=20, unique=True),
                ),
                ("expense_name", models.CharField(max_length=200)),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("PORTAL_WALLET_CHARGE", "Portal Wallet Charge"),
                            ("OFFICE_SUPPLIES", "Office Supplies"),
                            ("ELECTRICITY", "Electricity"),
                            ("INTERNET", "Internet"),
                            ("HARDWARE_MAINTENANCE", "Hardware Maintenance"),
                            ("OTHER", "Other Expense"),
                        ],
                        default="OTHER",
                        max_length=50,
                    ),
                ),
                (
                    "payment_mode",
                    models.CharField(
                        choices=[("ONLINE", "Online"), ("CASH", "Cash")],
                        default="CASH",
                        max_length=10,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("note", models.TextField(blank=True)),
                ("expense_date", models.DateField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="expenses",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-expense_date", "-created_at"],
            },
        ),
    ]
