# Generated by Django 4.2.22 on 2026-08-05 05:58

from django.db import migrations, models
import django.db.models.deletion


def get_or_create_tax(Tax, rate):
    existing = Tax.objects.filter(rate=rate).first()
    if existing:
        return existing
    return Tax.objects.create(
        tax_id=f'TAX-{rate}',
        name=f'Tax {rate}%',
        rate=rate,
        status='active',
        applied_to='both',
    )


def backfill_purchase_tax(apps, schema_editor):
    Purchase = apps.get_model('purchases', 'Purchase')
    PurchaseOrder = apps.get_model('purchases', 'PurchaseOrder')
    PurchaseReturn = apps.get_model('purchases', 'PurchaseReturn')
    Tax = apps.get_model('finance', 'Tax')

    for model in (Purchase, PurchaseOrder, PurchaseReturn):
        for row in model.objects.all():
            rate = row.tax_decimal_tmp
            if rate:
                tax = get_or_create_tax(Tax, rate)
                model.objects.filter(pk=row.pk).update(tax=tax)


class Migration(migrations.Migration):

    dependencies = [
        ('finance', '0004_seed_tax_from_taxrate'),
        ('purchases', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='purchase',
            old_name='tax',
            new_name='tax_decimal_tmp',
        ),
        migrations.RenameField(
            model_name='purchaseorder',
            old_name='tax',
            new_name='tax_decimal_tmp',
        ),
        migrations.RenameField(
            model_name='purchasereturn',
            old_name='tax',
            new_name='tax_decimal_tmp',
        ),
        migrations.AddField(
            model_name='purchase',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to the subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchases', to='finance.tax'),
        ),
        migrations.AddField(
            model_name='purchaseorder',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to the subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_orders', to='finance.tax'),
        ),
        migrations.AddField(
            model_name='purchasereturn',
            name='tax',
            field=models.ForeignKey(blank=True, help_text='Tax applied to the subtotal.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='purchase_returns', to='finance.tax'),
        ),
        migrations.RunPython(backfill_purchase_tax),
        migrations.RemoveField(
            model_name='purchase',
            name='tax_decimal_tmp',
        ),
        migrations.RemoveField(
            model_name='purchaseorder',
            name='tax_decimal_tmp',
        ),
        migrations.RemoveField(
            model_name='purchasereturn',
            name='tax_decimal_tmp',
        ),
    ]
