# Generated by Django 4.2.22 on 2026-08-12 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('purchases', '0002_alter_purchase_tax_alter_purchaseorder_tax_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='purchaseorder',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('received', 'Received'), ('paid', 'Paid'), ('partially_paid', 'Partially Paid')], default='pending', max_length=20),
        ),
    ]
