# Generated by Django 4.2.22 on 2026-07-28 11:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('masters', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_type', models.CharField(choices=[('dealer', 'Dealer'), ('retailer', 'Retailer'), ('mechanic', 'Mechanic')], max_length=20)),
                ('purpose', models.CharField(blank=True, max_length=200)),
                ('remarks', models.TextField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='visits/')),
                ('check_in_time', models.DateTimeField(auto_now_add=True)),
                ('check_in_lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('check_in_address', models.CharField(blank=True, max_length=500)),
                ('check_out_time', models.DateTimeField(blank=True, null=True)),
                ('check_out_lat', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_lng', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('check_out_address', models.CharField(blank=True, max_length=500)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], default='in_progress', max_length=20)),
                ('duration', models.DurationField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dealer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.dealer')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to=settings.AUTH_USER_MODEL)),
                ('mechanic', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.mechanic')),
                ('retailer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='visits', to='masters.retailer')),
            ],
            options={
                'ordering': ['-check_in_time'],
            },
        ),
    ]
