# Generated by Django 4.2.22 on 2026-07-31 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('visits', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='visit',
            name='mechanic',
        ),
        migrations.AlterField(
            model_name='visit',
            name='visit_type',
            field=models.CharField(choices=[('dealer', 'Dealer'), ('retailer', 'Retailer')], max_length=20),
        ),
    ]
